[theme]
primaryColor = "#FF69B4"        # Hot pink for buttons and highlights
backgroundColor = "#FFEBEB"     # Light pink for main background
secondaryBackgroundColor = "#FFF"  # Match main background for uniformity
textColor = "#C71585"          # Medium violet red for text
font = "sans serif"            # Clean font like Arial